export const USER = {
  LIST: {
    REQUEST: 'USER_LIST_REQUEST',
    SUCCESS: 'USER_LIST_SUCCESS',
    FAILURE: 'USER_LIST_FAILURE',
  },
  SHOW: {
    REQUEST: 'USER_SHOW_REQUEST',
    SUCCESS: 'USER_SHOW_SUCCESS',
    FAILURE: 'USER_SHOW_FAILURE',
  },
  CREATE: {
    REQUEST: 'USER_CREATE_REQUEST',
    SUCCESS: 'USER_CREATE_SUCCESS',
    FAILURE: 'USER_CREATE_FAILURE',
  },
  UPDATE: {
    REQUEST: 'USER_UPDATE_REQUEST',
    SUCCESS: 'USER_UPDATE_SUCCESS',
    FAILURE: 'USER_UPDATE_FAILURE',
  },
  DESTROY: {
    REQUEST: 'USER_DESTROY_REQUEST',
    SUCCESS: 'USER_DESTROY_SUCCESS',
    FAILURE: 'USER_DESTROY_FAILURE',
  },
}

const actionTypes = {
  USER,
}

export default actionTypes
